export { Genel, Context } from "./Genel";
export {Login} from "./Login"
export {Register} from "./Register"
export {Navbars} from "./Navbars"
export {TeacherApprove} from "./Admin"
export {ClassApprove} from "./Admin"
export {TeacherClassApprove} from "./Teacher"
export {TeacherClassGrade} from "./Teacher"
export { ClassCreate } from "./Teacher"
export { ClassSelect } from "./Student"
export { StudentClassGrade } from "./Student"
export { Calendar } from "./Calendar"